### ISSUE TITLE
Transport loading bug (rules)

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#3162]
This issue has been brought up on 
https://www.axisandallies.org/forums/index.php?topic=41580.0

### Engine version:
Tested with 1.9.0.0.9347,  also present in 7621 (so most likely introduced earlier)
### Map name and version:
Tested with WWII_Global_1940 and WWII_v5
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
A transport that has been part of a battle incorrectly loads units during Noncombat Move Phase
### Instead of this error, what should have happened?
Loading units should be prohibited.

Rulebooks say (Noncombat Move Phase):

> Transports can move to friendly coastal territories and load or
> offload cargo, **unless** they loaded, moved, offloaded, or were
> involved in combat during the Combat Move or Conduct
> Combat phase.

### Any additional information that may help:
test3.tsvg illustrates the issue for Global
test5.tsvg illustrates the issue for v5

[savedGames.zip](https://github.com/triplea-game/triplea/files/1757622/savedGames.zip)

**Comment by ron-murhammer** [comment]
@panther2 Any idea if this has ever been prohibited in any previous version? Just wondering if I need to see if something has changed in the past couple of months or if this was something that never was enforced.

**Comment by DanVanAtta** [comment]
> Any idea if this has ever been prohibited in any previous version?

I suspect this. @panther2 are there not also ruleset differences, or was it determined this was the right rule for all versions?

**Comment by panther2** [comment]
@redrum 
Having tested a bit I was able to reproduce this bug even with TripleA 1.8.0.9.
So I assume that this core rule has never been coded in.

@DanVanAtta 
Revised OOB (v2) was the last ruleset that allowed loading transports after combat.
Starting from and including Revised LHTR (v2 LHTR) this has changed!

**Comment by ron-murhammer** [comment]
@panther2 This should be fixed with https://github.com/triplea-game/triplea/pull/4834

**Comment by panther2** [comment]
@ron-murhammer I hope to find some time for testing soon.

**Comment by Cernelius** [comment]
Is this fix supposed to cover v2 LHTR too?

**Comment by panther2** [comment]
@ron-murhammer I have finally tested these scenarios using 1.10.14782 and can confirm, that they work correctly in wwII_Global and wwII_v5.

However in v2-LHTR the transport still incorrectly loads, despite having been part of the battle:

[testLHTRnewfile.zip](https://github.com/triplea-game/triplea/files/3247596/testLHTRnewfile.zip)

(cc: @Cernelius )

**Comment by ron-murhammer** [comment]
@panther2 @Cernelius Ah, yeah the fix didn't address v2-LHTR. Let me take a look at that map to see if there is an easy way to fix it as well.

**Comment by ron-murhammer** [comment]
#4857 should fix it for LHTR maps as well. I've tied doing the same transport check as v3 does now if the map sets the property of "LHTR Carrier production rules" to true which should only be maps based on LHTR rules. Not the cleanest solution but not much other choice without making larger changes.

**Comment by panther2** [comment]
@ron-murhammer The v2-LHTR scenario is resolved correctly now (tested with 1.10.786). Thank you.

**Comment by Cernelius** [comment]
Actually, it is not just this element. Despite the fact that TripleA threats sea transport rules exactly the same for Classic, Revised OOB and Revised LHTR, there is quite the number of differences amongst these 3 rulesets. So, the absence of a proper "LHTR" property for the transport differences, alike to the existent one for the carrier differences, is an actual general bug (or unsupported element). Also not having a general property "v2 LHTR Rules", or the like, I believe has been a major oversight.

**Comment by panther2** [comment]
@Cernelius Maybe reworking v1, v2 and v2-LHTR should be a separate topic/issue. 
It looks like there is a lot to do.

Personally I have been deeply involved starting with v3 and higher, but what we have discovered from the older versions so far implies more or less a major rework.

**Comment by Cernelius** [comment]
If tying to "LHTR Carrier production rules", I would suggest changing the name of this property to "LHTR naval rules". Then more elements could be added to it overtime, and it would work very closely as having a general property for setting the v2 LHTR ruleset (bad decision of the past not having made it, like instead done for v2 OOB).

**Comment by panther2** [comment]
As the initial flaw has been fixed I am closing this issue. Reworking v1 and v2, v2 LHTR in whatever way should be initiated by separate issues, IMHO.
