### ISSUE TITLE
No limit on minor industrial complex placement.

### ISSUE THREAD

**Issue by gg405** [triplea-game/triplea#3359]
### Engine version
1.9.0.0.9687

### My Operating System
Windows 10

### Map name
World War II Pacific 1940 2nd Edition

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
1. Capture Korea as United States
2. Build minor industrial complex in Korea.
3. On a later turn, build a 2nd minor industrial complex in Korea (and potentially, more)
4. Profit.

### Instead of this error, what should have happened?
According to page 22 of the latest rules:

"Minor industrial complexes can be built only in territories with an IPC value of 2 or higher. **You can’t have more than one facility of the same type (industrial complex, air base, or naval base) per territory.** "

**Comment by asvitkine** [comment]
I assume this is actually a map bug.

**Comment by VictoryFirst2** [comment]
This is a map-related bug that affects not only this map but also World War II Europe and World War II Global (and potentially other maps too).

If you look at the XML in each of those games, you can see the property maxFactoriesPerTerritories set to 2. This is because the factoryUpgrade unit essentially functions as a major factory, except that it consumes (and must consume) a minor factory during placement. But, as this unit counts as a factory, in order to place it, maxFactoriesPerTerritories needs be 2. If it's 1, then territories containing a factory wouldn't be eligible for placement of factoryUpgrade.

However, this allows players to place other factories that are not factoryUpgrade in these territories as well. This results in the player being able to place a minor factory in a territory that already contains a minor or major factory. The number of factories is limited to 2 though, so the original bug report is incorrect in saying that there is no limit.

The fix is simple, however it would mean that the XMLs of each of these games need to be updated. Europe and Pacific are not played that much, but Global is probably the most played TripleA map. Updating that map would require everyone to redownload the map. I hope that isn't a problem.

@WCSumpton What do you think?

**Comment by VictoryFirst2** [comment]
I suggest the following fix:

Modify the unitAttachment of "factory_upgrade". Break "isFactory" into the option attachments it automatically sets, then set "constructionType = factory_upgrade". Also, set the game property "maxFactoriesPerTerritory" to 1.
```
    <attachment name="unitAttachment" attachTo="factory_upgrade" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
      <option name="canBeDamaged" value="true"/>
      <option name="isInfrastructure" value="true"/>
      <option name="canProduceUnits" value="true"/>
      <option name="isConstruction" value="true"/>
      <option name="constructionType" value="factory_upgrade"/>
      <option name="constructionsPerTerrPerTypePerTurn" value="1"/>
      <option name="maxConstructionsPerTypePerTerr" value="1"/>
      ...
    </attachment>
```
Because the constructionTypes of factory_minor/major and factory_upgrade are now different, factoryUpgrade can be placed in territories with a minor factory, and minor factories cannot be placed in territories already containing a minor/major factory.

I tested it briefly and it looks like it's working, but further testing might be a good idea.

Right now, I can confirm that the following maps would require this change in every included XML:

- world_war_ii_pacific
- world_war_ii_europe
- world_war_ii_global

And probably also in all these ones that are based on Global:

- World_War_II_Halifax
- ww2global40_ryuzaki
- young_grasshoppers_tournament_edition
- uhd_world_war_ii_global
- oztea_1939_global
- oztea_1942
- Operation_Unthinkable
- charles_de_gaulle_1939
- 41_oztea

**Comment by frigoref** [comment]
> ... If you look at the XML in each of those games, you can see the property maxFactoriesPerTerritories set to 2. This is because the factoryUpgrade unit essentially functions as a major factory, except that it consumes (and must consume) a minor factory during placement. ...

Is the property `maxFactoriesPerTerritories` only used to accommodate factory upgrades or are there maps that allow more than one factory in territories?

**Comment by VictoryFirst2** [comment]
> * world_war_ii_pacific
> * world_war_ii_europe
> * world_war_ii_global

@frigoref In the three maps listed above, you are not allowed to have more than one factory in a territory. But due to a suboptimal XML, if maxFactoriesPerTerritories was 1, then factory upgrades wouldn't be able to be placed as that is a unit that counts and functions as a factory, but consumes factory_minor. So the engine in this situation probably marks all territories that already contain a factory ineligible for placement because when trying to place a factory upgrade in a territory containing a factory_minor, nothing happens. It seems that because of this, maxFactoriesPerTerritories was 2, but this unintentionally created the possibility for the player to place up to two factories of any type in a territory.

As for all the other maps listed, I am not 100% sure. It is possible that there is a map that actually does allow multiple factories per territory, but I doubt it. The three maps listed above definitely do NOT allow this.

**Comment by Cernelius** [comment]
Sounds like chronic dirty hacking over many years has made this issue generally unfixable without arguably undue time investment.

The root issue causing the present issue was that the limit at 1 for `maxFactoriesPerTerritories` was (and I assume still is) not working with upgrade dynamics, so, instead of fixing this problem, it was used the work-around of setting the limit at 2 in games to circumvent the badly working program enforcement.

This hack, however, had the byproduct of causing the problem described at this issue (and likely not only this case).

Now, even if the problem is fixed at the program level, all those games with limit at 2 - which should have had the limit at 1 had the program worked properly - will remain around and keep having this problem unless finding every single one of them and de-hacking them.

**Comment by Cernelius** [comment]
In theory, if you fix the program, then you could also fix every map using this specific hack by making a mass substitution in every game file in the entire TripleA repository of every instance of
`property name="maxFactoriesPerTerritory" value="2"`
with
`property name="maxFactoriesPerTerritory" value="1"`

However, this would have one major and one minor problem.

The major problem is that you would damage (likely badly) every game which has this value set correctly (and needs it to remain at 2).

The minor problem is that the maps having the hack removed would only work properly with the fixed program, so you may easily have users using unupdated maps and/or game-saves with updated engines and vice versa having problems (in particular, users updating a map having a game formerly using this hack (or playing a game-save given to them by someone hosting the game who updated the map) while not updating the program will be unable to upgrade factories).

**Comment by VictoryFirst2** [comment]
Well said. The task would be to gather all maps based on the XML of Global 1940, and then examine in each one if the maxFactoriesPerTerritory = 2 is an actual game feature or simply copied from G40, where it is a hack.

A simpler approach would be to fix this only in the three "core" modules:
* world_war_ii_pacific
* world_war_ii_europe
* world_war_ii_global

as these are the main modules for the corresponding A&A games. 

All the other modules aren't played/used much, so a fix there might not be as valuable as it is in for example world_war_ii_global, arguably the most played TripleA module. Perhaps this can be extended to include 1-2 of the most played variants (i.e. UHD_world_war_ii_global could be a good candidate).

If the fix would be limited to just a couple of XMLs, then the entire fix will not take that much time as then it is just a matter of copy/pasting stuff in like 10-15 files or something. Not that time-consuming.

As with regards to the players not updating their map, I don't understand why you would do that as those players would get a pop-up saying one of their maps is out of date every time they load TripleA, once the fix has been made to the XML and triplea-maps.yaml. So in theory, yes, if they don't update, then it will not work for them and for whoever they are playing. But in practice, most people will probably update and also if we announce this somewhere on A&A.org and the TripleA forum, then that will definitely draw some attention and people will be aware of the fact that there has been a bug in those modules for all this time and updating their map would fix it.

To clarify, simply changing the maxFactoriesPerTerritory to 1 is not enough to fix it. The code for factory_upgrade also needs to be modified (more precisely, the constructionType needs to be something else than "factory"), otherwise factory_upgrades wouldn't be able to be placed at all. Also, there is no need to "fix the program", assuming you mean TripleA by that, as TripleA does everything correctly. This is simply something that can and - in my opinion - should be solved at XML level.

**Comment by Cernelius** [comment]
> To clarify, simply changing the maxFactoriesPerTerritory to 1 is not enough to fix it.

Yes. That's why I said a fix at the program level is needed. However, I agree, without a fix at the program level, that is of course not enough: it would fix the problem at this issue but introduce much bigger problems.

>The code for factory_upgrade also needs to be modified (more precisely, the constructionType needs to be something else than "factory"), otherwise factory_upgrades wouldn't be able to be placed at all.

I guess this depends on what fix is done at the program level.

>Also, there is no need to "fix the program", assuming you mean TripleA by that, as TripleA does everything correctly. This is simply something that can and - in my opinion - should be solved at XML level.

No. The root problem here is that, when you upgrade something, the program understands that you are going to have two units in the zone (in this case, two factories), instead of upgrading one unit to an other unit, whereas in practice the unit (the factory) remains only one, just gets upgraded. Thereby, the fix would be that, for example, if the `maxFactoriesPerTerritory` is equal to 1, the program allows to upgrade a single factory to an other single factory, without reacting as if you are placing a second factory in the zone. However, the fix should be generally for whatever `maxConstructionsPerTypePerTerr` when upgrading units.

**Comment by Cernelius** [comment]
Of course, such a fix would create problems for every game which is currently hacking around the problem by increasing the value of the `maxConstructionsPerTypePerTerr` unit option (I'm thinking about games with a lot of upgrades like "Civil War", but I don't actually know if it is relevant for this game.), but at least would allow future games to be well done on this respect, and of course anybody can go back and fix existent ones.

However, this is not a very bad problem for already thus hacked maps so long as the rules of those games are clear and there is no AI in play because knowledgeable human players can limit themselves from placing more than they should according to the rules.

**Comment by frigoref** [comment]
The engine logic has priority and the map XMLs have to follow. 
We first need a fix and then (before we merge this fix) we check how to adjust map XML on servers/ on player drives.
For a period of time we could think of checking for an upgradable factory in the XML and reduce the `maxFactoriesPerTerritory` by 1 (if >1).
Then a later map fix can be combined with undoing this temporary workaround. 
I'd suggest to work on the first fix before overthinking things.

**Comment by VictoryFirst2** [comment]
@frigoref @Cernelius I understand that an engine fix might be preferred but I have the feeling this is easier said than done. The factory_upgrade cannot be placed if `maxFactoriesPerTerritory` is 1 because the engine will not allow two factories in a territory, even when one is consumed during placement and there would be only one left. The necessary fix would be to somehow create an exception case when the user tries to place a factory in a territory that contains a factory that that new factory consumes. This fix should apply to all units with `constructionType` 'factory', and should allow only one extra placement of the factory_upgrade and not multiple.

One more complication arises when we consider non-factory units. As `constructionType` can be anything, you could have units airbase_minor, airbase_major, and airbase_upgrade all labeled as `constructionType` "airbase", and where airbase_upgrade consumes an airbase_minor during placement. Then, if `maxConstructionsPerTerritory` is 1, a similar problem would occur where airbase_upgrade wouldn't be able to be placed. A simple work-around for this is to make airbase_upgrade a different `constructionType` in the XML, e.g. "airbase_upgrade". This fix is so much simpler than an engine fix that checks if the constructionTypes are the same and if airbase_upgrade is placed in a territory containing a unit it would consume. That's why I initially suggested an XML-only fix. The engine change might result in new bugs, whereas the XML change would 100% solve everything and definitely not introduce new bugs.

**Comment by Cernelius** [comment]
>The necessary fix would be to somehow create an exception case when the user tries to place a factory in a territory that contains a factory that that new factory consumes. This fix should apply to all units with `constructionType` 'factory', and should allow only one extra placement of the factory_upgrade and not multiple.

No. As I said, "the fix should be generally for whatever `maxConstructionsPerTypePerTerr` when upgrading units", the fix has actually nothing to do with the unit being a factory. It should apply to whatever unit. For example, if a "trench" upgrades to "bunker" and they are both  `<option name="constructionType" value="emplacement"/>` and `<option name="maxConstructionsPerTypePerTerr" value="4"/>`, and you have 4 trenches on a zone, then the engine should allow you to upgrade as many of those trenches as you want to bunkers provided that you are not upgrading on the same turn more than what is allowed by the `constructionsPerTerrPerTypePerTurn`.

> One more complication arises when we consider non-factory units.

Being a factory should be just out of the considerations as irrelevant. This is related to constructions, not factories. Just it's a fact that factories are usually costructions. `maxFactoriesPerTerritories` is just something which is only indirectly relevant as it determines the `maxConstructionsPerTypePerTerr` of the unit or units calling it. Once the basis is fixed, I assume that should be fixed too.

>As `constructionType` can be anything, you could have units airbase_minor, airbase_major, and airbase_upgrade all labeled as `constructionType` "airbase", and where airbase_upgrade consumes an airbase_minor during placement. Then, if `maxConstructionsPerTerritory` is 1, a similar problem would occur where airbase_upgrade wouldn't be able to be placed.

Indeed.

**Comment by Cernelius** [comment]
@VictoryFirst1:
> I suggest the following fix:
> 
> Modify the unitAttachment of "factory_upgrade". Break "isFactory" into the option attachments it automatically sets, then set "constructionType = factory_upgrade". Also, set the game property "maxFactoriesPerTerritory" to 1.
> 
> ```
>     <attachment name="unitAttachment" attachTo="factory_upgrade" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
>       <option name="canBeDamaged" value="true"/>
>       <option name="isInfrastructure" value="true"/>
>       <option name="canProduceUnits" value="true"/>
>       <option name="isConstruction" value="true"/>
>       <option name="constructionType" value="factory_upgrade"/>
>       <option name="constructionsPerTerrPerTypePerTurn" value="1"/>
>       <option name="maxConstructionsPerTypePerTerr" value="1"/>
>       ...
>     </attachment>
> ```
> 
> Because the constructionTypes of factory_minor/major and factory_upgrade are now different, factoryUpgrade can be placed in territories with a minor factory, and minor factories cannot be placed in territories already containing a minor/major factory.
> 
> I tested it briefly and it looks like it's working, but further testing might be a good idea.

I've no doubt it's working to fix this issue, but it is not an actual fix: just you would be exchanging a work-around with bad side effects for an other work-around with bad (albeit more limited) side effects. I guess we can ask ourselves if the new work-around is better or worse, but I'm very uninterested in this.

About the bad side effects of your workaround, am I correct to assume that what you are proposing is substituting the line

```
      <option name="isFactory" value="true"/>
```

in `attachment name="unitAttachment" attachTo="factory_upgrade"`

with the lines
```
      <option name="canBeDamaged" value="true"/>
      <option name="isInfrastructure" value="true"/>
      <option name="canProduceUnits" value="true"/>
      <option name="isConstruction" value="true"/>
      <option name="constructionType" value="factory_upgrade"/>
      <option name="constructionsPerTerrPerTypePerTurn" value="1"/>
      <option name="maxConstructionsPerTypePerTerr" value="1"/>
```

Plus changing from `2` to `1` the value of `maxFactoriesPerTerritory`

If this is what you want to do, the net result will be that you fix this issue (being able to place a second "factory_minor" where you already have one), but you still have the issue of being able to place a "factory_minor" where you have a "factory_upgrade". Indeed, this would make the side effects of the work-around a lot more limited but at the price of having an even harder to fix hack if/once the program is actually fixed (because now it would not be just a matter of turning a "2" into a "1" in a single place in the game file). (I've not tested this for the mentioned games.)

>A simple work-around for this is to make airbase_upgrade a different `constructionType` in the XML, e.g. "airbase_upgrade". This fix is so much simpler than an engine fix that checks if the constructionTypes are the same and if airbase_upgrade is placed in a territory containing a unit it would consume. That's why I initially suggested an XML-only fix. The engine change might result in new bugs, whereas the XML change would 100% solve everything and definitely not introduce new bugs.

Look. As you say, it's a work-around. Even if it would be a perfectly clean work-around 100% solving everything (which is not: it just reduces the problems), I'm really not seeing the point of exchanging a hack for an other (better?) hack instead of actually fixing things (if you can). If the developers agree that things are not fixable, then I guess we can start thinking about hacking around... Mind you that I'm not a developer: I've no idea about how to fix the program.

**Comment by VictoryFirst2** [comment]
> If this is what you want to do, the net result will be that you fix this issue (being able to place a second "factory_minor" where you already have one), but you still have the issue of being able to place a "factory_minor" where you have a "factory_upgrade".

Good catch, I missed that... In that case, I don't see a clean way to solve this using the XML only and I take back everything I said. This must be solved on the engine level, no matter how hard it will be.

Still, we need to carefully test and consider all possibilities when working on this fix to avoid introducing new bugs. I feel this can easily happen with a problem like this.

**Comment by Cernelius** [comment]
@VictoryFirst1:
>no matter how hard it will be.

I want to make clear that the problem which I called a "minor problem" is in my opinion something which we can simply ignore/accept, at most trying to inform users via forum or whatever.

@VictoryFirst1:
>As with regards to the players not updating their map, I don't understand why you would do that as those players would get a pop-up saying one of their maps is out of date every time they load TripleA, once the fix has been made to the XML and triplea-maps.yaml. So in theory, yes, if they don't update, then it will not work for them and for whoever they are playing. But in practice, most people will probably update and also if we announce this somewhere on A&A.org and the TripleA forum, then that will definitely draw some attention and people will be aware of the fact that there has been a bug in those modules for all this time and updating their map would fix it.

Yes, this is a minor problem we should not worry too much or at all about.

---

As for the "maior problem", namely (quoting myself)

>The major problem is that you would damage (likely badly) every game which has this value set correctly (and needs it to remain at 2).

maybe is not a problem at all even in case of mass change. I just don't know if there are maps out there being in such a condition. Indeed, it is not a problem at all if you just fix a few "important" maps and leave alone the rest.

---

Summarising, if you can fix the problem at the engine level and then fix the game file (XML) of a few maps, do it and don't worry too much or at all for any side issues. The only actual issues are for the maps hacking around this problem and not having an active developer updating them, and I don't think TripleA should support abandoned hacks.

**Comment by VictoryFirst2** [comment]
Hacked together something that should fix this on the engine level without creating new bugs. If this gets merged, what remains is to update the relevant XMLs. Will discuss this with Gamerman01 on the A&A forum on how to best do this.

**Comment by Cernelius** [comment]
Will this allow to upgrade X units (together) when the limit per zone on both upgradable and upgraded units together is Y and the number of such upgradable units in the territory is greater than the difference between Y and X, with X equal or greater than 1 and Y equal or greater than X?

The example I made is
>if a "trench" upgrades to "bunker" and they are both `<option name="constructionType" value="emplacement"/>` and `<option name="maxConstructionsPerTypePerTerr" value="4"/>`, and you have 4 trenches on a zone, then the engine should allow you to upgrade as many of those trenches as you want to bunkers provided that you are not upgrading on the same turn more than what is allowed by the constructionsPerTerrPerTypePerTurn.

(I mean also being able to upgrade them all at once with a single prompt.)

**Comment by VictoryFirst2** [comment]
@Cernelius Good catch, I tested and with the PR the engine would only allow you to place one bunker at at time, until all 4 have been placed.

This can probably be easily fixed.

**Comment by VictoryFirst2** [comment]
@Cernelius updated the PR. Currently, if you have X upgradable units in a territory and you want to upgrade Y of them and the limit is maxConstructionsPerTypePerTerr, with X≥Y, and X+Y>maxConstructionsPerTypePerTerr, the cap will be increased with X. This means:
Cap = maxConstructionsPerTypePerTerr + X ≥ X + Y

This ensures the cap is always large enough to place everything.

So in your example:
4 trenches in a zone
X = 4
Let's say you want to place 4 bunkers
Y = 4
Limit is 4 constructions per territory
maxConstructionsPerTypePerTerr = 4
Now, the engine will allow you to place maxConstructionsPerTypePerTerr + X = 4 + 4 = 8 of that constructionType in the territory.

**Comment by Cernelius** [comment]
> [@Cernelius](https://github.com/Cernelius) updated the PR. Currently, if you have X upgradable units in a territory and you want to upgrade Y of them and the limit is maxConstructionsPerTypePerTerr, with X≥Y, and X+Y>maxConstructionsPerTypePerTerr, the cap will be increased with X. This means: Cap = maxConstructionsPerTypePerTerr + X ≥ X + Y
> 
> This ensures the cap is always large enough to place everything.
> 
> So in your example: 4 trenches in a zone X = 4 Let's say you want to place 4 bunkers Y = 4 Limit is 4 constructions per territory maxConstructionsPerTypePerTerr = 4 Now, the engine will allow you to place maxConstructionsPerTypePerTerr + X = 4 + 4 = 8 of that constructionType in the territory.

I would test the following two cases.

I can have at most 4 trenches + bunkers in a territory, but (for whatever reasons) there are already 8 trenches in a territory and no bunkers. Verify that the program allows me to upgrade up to 4 trenches to bunkers in the territory at once (ending up with 4 trenches and 4 bunkers) but no more.

Assuming we have an other unit called pillbox which is exactly the same as the trench (for placement) except that it cannot be upgraded to bunker and that I can have at most 4 trenches + bunkers + pillboxes in a territory, and there are already 2 trenches in a territory and no bunkers nor pillboxes. Verify that the program allows me to place up to 2 bunkers and 2 pillboxes in the territory at once (ending up with 2 bunkers and 2 pillboxes) but not 1 bunker and 3 pillboxes at once (because in the latter case I would end up with 1 trench, 1 bunker and 3 pillboxes, for a total of 5 units).

**Comment by Cernelius** [comment]
In the two cases at my previous post, be sure to set `constructionsPerTerrPerTypePerTurn` high enough which it does not matter (Unfortunately, it is not possible to set it to infinite.).

**Comment by VictoryFirst2** [comment]
> I can have at most 4 trenches + bunkers in a territory, but (for whatever reasons) there are already 8 trenches in a territory and no bunkers. Verify that the program allows me to upgrade up to 4 trenches to bunkers in the territory at once (ending up with 4 trenches and 4 bunkers) but no more.

I don't understand this. How can you have at most 4 trenches + 4 bunkers in a territory? If they have the same constructionType, you can have any combination in a territory (5/3, 6/2, 8/0, etc.). Then, having 8 trenches in a territory and upgrading 4 of them to bunkers would be a similar situation as what I already tested, which is working.

> Assuming we have an other unit called pillbox which is exactly the same as the trench (for placement) except that it cannot be upgraded to bunker and that I can have at most 4 trenches + bunkers + pillboxes

Here same thing, what is meant with 4 trenches + bunkers + pillboxes? Is that 4 of each, meaning 12 of that constructionType?

**Comment by Cernelius** [comment]
With
>I can have at most 4 trenches + bunkers in a territory

I meant that trench and bunker both have `<option name="constructionType" value="emplacement"/>` and `<option name="maxConstructionsPerTypePerTerr" value="4"/>`.

With
>I can have at most 4 trenches + bunkers + pillboxes in a territory

I meant that trench, bunker and pillbox all have `<option name="constructionType" value="emplacement"/>` and `<option name="maxConstructionsPerTypePerTerr" value="4"/>`.

**Comment by beelee1** [comment]
@VictoryFirst1 does the PR allow exceeding the max built then ? Can it allow more than there should be ? 

If so, I made an xml hack by creating a separate unit that allows the extra placement. It changes into the unit that is maxed out after placed and then is removed.

It allows you to overplace if you don't PlayerEnforce the correct amount purchased but makes it easier to track as opposed to just making the max place higher.

E.g. in UHD Boxes you can only have 6 Waffen Inf and 4 Oberst. The Oberst consume a Waffen Inf. Currently I have max place of 10 Waffen Inf to allow correct placement. This is hard to track because you have to look at all the TTys the Waffen Inf could be in, add them up so you don't overplace.

With the new unit, you can still overplace but only by buying too many of the new unit.

<img width="772" height="544" alt="Image" src="https://github.com/user-attachments/assets/ff037ab6-a4c5-4c89-a886-c8ecbcdf3a61" />

So if the Engine update requires PlayerEnfocement still, the above is a way around it without changing the engine.

Also, some maps do have multiple Factories in the same territory. They may not have "isFactory" but have all the stuff making them a Fctry. I have used this for creating a "Barracks" unit that places Infantry only and can be placed in TTys regular Fctrys can't, as well as placing where there is a Fctry.

I don't remember the specifics and it may require the Barracks to Player Enforce Infantry only builds when in a TTy with a regular Fctry. Otherwise they work correctly.

If your PR fixes it so their is no PlayerEnforcement, Then Rock On ! but it seems kinda tricky and may have unintended consequences, such as limiting to only 1 Fctry

**Comment by Cernelius** [comment]
>How can you have at most 4 trenches + 4 bunkers in a territory?

I meant at most 4 units in the territory amongst trenches and bunkers (so respectively 4, 0; 3, 1; 2, 2...).

>what is meant with 4 trenches + bunkers + pillboxes? Is that 4 of each, meaning 12 of that constructionType?

No: it's 4 of that construction type in total, they all having the same type, meaning at most 4 units in the territory amongst trenches, bunkers and pillboxes (so respectively 4, 0, 0; 3, 1, 0; 2, 2, 0; 2, 1, 1...).

**Comment by VictoryFirst2** [comment]
@beelee1 The engine change only allows what is possible by the rules. If you try to overplace, the action gets caught by other error handlings, like "Not enough units to upgrade or be consumed" or "Too many constructions in {terr}" or "No more constructions allowed in {terr}". I tested a bunch of things and never was allowed to do something illegal.

Currently, the engine change is only set to work for constructions. It does not work yet for regular units, but I think it can be easily extended. If it gets extended, the hack in EXP wouldn't be needed and you should be able to place the oberst just fine.

**Comment by Cernelius** [comment]
> I can have at most 4 trenches + bunkers in a territory, but (for whatever reasons) there are already 8 trenches in a territory and no bunkers. Verify that the program allows me to upgrade up to 4 trenches to bunkers in the territory at once (ending up with 4 trenches and 4 bunkers) but no more.

For example, this would be the situation of a game in which I can never place trenches so to exceed the maximum of 4 per territory (actually never more than 4 units per territory summing up trenches and bunkers), but at the start of the game (in the starting setup) I have a territory with 8 trenches already in it. (Of course, there can be other cases, like trenches being able to move or triggered placement of trenches.)

**Comment by VictoryFirst2** [comment]
> I can have at most 4 trenches + bunkers in a territory, but (for whatever reasons) there are already 8 trenches in a territory and no bunkers. Verify that the program allows me to upgrade up to 4 trenches to bunkers in the territory at once (ending up with 4 trenches and 4 bunkers) but no more.

This works, although I don't think it's a desirable thing as you can't have 8 trenches in a territory anyway, nor 4 trenches and 4 bunkers. Nevertheless, the engine allows you to upgrade up to 4 trenches to bunkers.

> Assuming we have an other unit called pillbox which is exactly the same as the trench (for placement) except that it cannot be upgraded to bunker and that I can have at most 4 trenches + bunkers + pillboxes in a territory, and there are already 2 trenches in a territory and no bunkers nor pillboxes. Verify that the program allows me to place up to 2 bunkers and 2 pillboxes in the territory at once (ending up with 2 bunkers and 2 pillboxes) but not 1 bunker and 3 pillboxes at once (because in the latter case I would end up with 1 trench, 1 bunker and 3 pillboxes, for a total of 5 units).

The program now allows you to place 1 bunker and 3 pillboxes, so this doesn't work. Thanks for this test. Will try if I can correct this.

EDIT the pillboxes were actually not necessary for the above test. If you have 4 trenches in a territory, you can place 2 bunkers and 2 trenches, giving you 4 trenches and 2 bunkers, exceeding the max.

**Comment by Cernelius** [comment]
> > I can have at most 4 trenches + bunkers in a territory, but (for whatever reasons) there are already 8 trenches in a territory and no bunkers. Verify that the program allows me to upgrade up to 4 trenches to bunkers in the territory at once (ending up with 4 trenches and 4 bunkers) but no more.
> 
> This works, although I don't think it's a desirable thing as you can't have 8 trenches in a territory anyway, nor 4 trenches and 4 bunkers. Nevertheless, the engine allows you to upgrade up to 4 trenches to bunkers.

Well, I would argue that you CAN have 8 trenches in a territory (if only because nothing stops you from having this numer in the "unit initialize", which is the starting setup). You just cannot increase their number above 4 during the placement phase. We could argue that having more in the starting setup or with triggering is bad game-making, but we cannot argue that we can have constructions able to move (because nothing says that constructions must have movement 0 and cannot be transported unless this gets enforced at the program level or documented in Pact of Steel 2 as something to which the game-makers should abide). Obviously, this should not be the case of something called "trench", but that is just a name.

**Comment by Cernelius** [comment]
> EDIT the pillboxes were actually not necessary for the above test. If you have 4 trenches in a territory, you can place 2 bunkers and 2 trenches, giving you 4 trenches and 2 bunkers, exceeding the max.

Yah. This is the most important thing to fix. Mind you that my use of X and Y was different from yours, but I'm not a developer so you go the way you feel it's best. 👍 

Regarding the less important the case of having 8 trenches in a territory with the max at 4 (for trenches and bunkers summed up), one could argue that you should be able to place 8 bunkers in that territory since that would not actually increase the actual max (which would be exceeded by 4 before as well as after, going from a territory with 8 trenches and no bunkers to one with 8 bunkers and no trenches).

**Comment by Cernelius** [comment]
> Regarding the less important the case of having 8 trenches in a territory with the max at 4 (for trenches and bunkers summed up), one could argue that you should be able to place 8 bunkers in that territory since that would not actually increase the actual max (which would be exceeded by 4 before as well as after, going from a territory with 8 trenches and no bunkers to one with 8 bunkers and no trenches).

However, this feels wrong to me. The solution which I gave (max 4 trenches and 4 bunkers when starting with 8 trenches and 0 bunkers even though the max is at 4 for both summed up) is just what feels right to me. However, either solution would be reasonable, in my opinion.

**Comment by VictoryFirst2** [comment]
> However, this feels wrong to me. The solution which I gave (max 4 trenches and 4 bunkers when starting with 8 trenches and 0 bunkers even though the max is at 4 for both summed up) is just what feels right to me. However, either solution would be reasonable, in my opinion.

Agreed. I think having 8 trenches in a territory with only 4 allowed is wrong to begin with, but to allow the program to upgrade 4 to bunkers seems the most appropriate to me.

Unfortunately I have bad news and that is I'd need to rewrite the whole method to disallow the player to place more constructions than is allowed. This is because the method currently looks at each constructionType, and determines how many of that constructionType can be placed in a territory. It doesn't look at the individual units. That's why the engine is allowing you to place 2 trenches and 2 bunkers when you have 4 trenches in a territory. It doesn't know you are not placing the actually allowed 4 bunkers because bunker and trench have the same constructionType. It treats them all the same.

I think it is possible to rewrite the method by looking at individual units and keeping the constructionType as secondary information, but that will take some time.

**Comment by Cernelius** [comment]
Bummers. Looks like this is very hard to fix? I think it is a fairly important problem for complex maps (like "Civil War").

**Comment by VictoryFirst2** [comment]
@Cernelius I updated PR draft to something that fixed the issue of being able to place more constructions than you are technically allowed. I think everything should now work correctly. Can you come up with a couple of test scenarios so that I can check if the program correctly handles these situations?

**Comment by VictoryFirst2** [comment]
@beelee1 If I understand correctly, the EXP problem (https://github.com/triplea-game/triplea/issues/3359#issuecomment-4667145186) has to do with maxBuiltPerPlayer? So the engine would normally prevent you from purchasing the unit, or only placing? Is the unit defined as a construction with a constructionType?

**Comment by Cernelius** [comment]
> [@Cernelius](https://github.com/Cernelius) I updated PR draft to something that fixed the issue of being able to place more constructions than you are technically allowed. I think everything should now work correctly. Can you come up with a couple of test scenarios so that I can check if the program correctly handles these situations?

Cool. Maybe the ones we've already talked about are good enough, I guess. Not much more ideas right now. I'll think about it. Not right now.

**Comment by VictoryFirst2** [comment]
@Cernelius No worries, I already tested a lot of scenarios and they all worked correctly. I think the PR is ready for review, and possibly merging too.

**Comment by Cernelius** [comment]
> [@Cernelius](https://github.com/Cernelius) No worries, I already tested a lot of scenarios and they all worked correctly. I think the PR is ready for review, and possibly merging too.

Cool. I would say go ahead. I think we already went pretty deep. I can still eventually try to break the system with something strange after you merged it and get back to you (right?).

There will also be a lot of work (if anyone is willingly) about updating all the hacked maps. For example, Pulicat's "Civil War". (But not necessary.)

**Comment by VictoryFirst2** [comment]
@Cernelius The PR is really cool because if it was merged, the XML-hacking wouldn't be necessary anymore. Unfortunately I don't think a popular map like G40 can ever be fixed because they are played a lot and the people there don't like changes and updates, even if they improve the map (had a talk with gamerman01 about this). Nevertheless, any less popular or new map would benefit from it.

And sure, after merging you can try your best to break it! That will probably work better than trying to test everything beforehand.

**Comment by Cernelius** [comment]
Not sure, but I'm not voluntering to touch Global either, but of course this will not fix the problem at this issue unless the game itself is de-hacked (actually, it will make the problem worse for the hacked games but nothing major). In the spirit of not supporting hacks, I'm totally on board with merging this anyway.

If anyone will want to fix the Global 1940 2nd game, this is what needs to be done after this issue is fixed at the program level.

1. Open https://github.com/triplea-maps/world_war_ii_global/blob/master/map/games/ww2global40_2nd_edition.xml in a text editor.
2. Change `property name="maxFactoriesPerTerritory" value="2" editable="false"` to `property name="maxFactoriesPerTerritory" value="1" editable="false"`.

CC: @panther2

(Is anyone in touch with the Global community willing to do that and look out in case of any problems?)

**Comment by Cernelius** [comment]
However, doing the above will cause major problems for those who update the map but not the program (namely, not being able to upgrade any factories), so it would be needed to advise the community (maybe @panther2 can do that?) to update both TripleA and the map (or at least not only the map).

**Comment by VictoryFirst2** [comment]
yeah exactly, the updates need to be coordinated which is hard for a large mass of players. In theory, it could be done though. It just needs to be organized well-enough.

**Comment by Cernelius** [comment]
@DanVanAtta @frigoref I think everyone should receive a notification to upgrade TripleA as soon as this PR is merged.

**Comment by VictoryFirst2** [comment]
@Cernelius It'd be great if this bug could be solved as well this way: https://github.com/triplea-game/triplea/issues/4685. Unfortunately, that would require updating a ton of XMLs, not just a couple. That's because the wording of the property canMoveUnitsOverOwnedLand is unclear and calls for a need of two separate properties. If we can somehow mass-update the most popular XMLs and force users to update their TripleA version, it could be done though.

**Comment by panther2** [comment]
@VictoryFirst2 @Cernelius 

Awesome work and thoughts! In general I would say that a further development of the engine should not be prevented by the possible reluctance of a group of users to update.
However, as Global19402E and its derivates are most popular, the question of how to proceed deserves some deep thoughts, for sure.

One additional question:
Let's assume the engine fix is merged and the games in question are modified xml-wise.
How would that affect games already started?

Ususally map-updates don't affect ongoing games, as all information is read from the savegame that contains the "old status quo".
But what happens when a game-engine update is applied, too?

**Comment by Cernelius** [comment]
I assume playing an old save-game with the new program would have exactly the same issue as playing an non-updated map (which are probably going to be most of them), meaning a map which has still the hack, with the new program (if @asvitkine can confirm).

This issue would be that now you can actually have two factories per territory, meaning that you still have all the problems at this issue plus also the fact that you would be able to upgrade one or two minor factories to major factories in a territory with two minor factories in it. Since putting a second minor factory in the same territory is a waste of money, really almost no problem at all.

To summarise (assuming the PR works perfectly):
1. If you update both the program and the map, everything will be fine.
2. If you update the program but not the map or update the program and play an old save, you have almost no additional problem at all (practically irrelevant), and you will still have all the problems which you already have (like being able to place a useless second minor factory, but now you can also upgrade a second useless factory to major).
3. If you do not update the program but update the map, you will have the problem at this issue fixed but will not be able to upgrade minor factories to major factories (The hack of allowing 2 factories per territory (contrary to the rules) existed only to make this possible.). The simple work-around would be to add a major factory with edit mode, remove the minor factory with edit mode and adjust the money with edit mode. Practically, it is just needed somebody who keeps a look on the Axis Forum, and when someone reports that he cannot upgrade the factories tell the user that he needs to update the program but can also do it using edit mode if he knows the rules and costs.

(This assumes that someone updates the Global game as I detailed (changing `name="maxFactoriesPerTerritory" value="2"` to `name="maxFactoriesPerTerritory" value="1"`. If @asvitkine does not do it and nobody else does it, the only outcome is that eventually everyone will be on situation number 2, which means having all the problems we currently have and more, but the additional problems are virtually irrelevant, and nobody can ever be in situation number 1 or 3, so practically nothing important changes.)

Long story short, as long as I'm getting everything right and the PR works perfectly, there will be no major problems anyway, but this PR is fixing ABSOLUTELY NOTHING on its own for the hacked games (and actually it's making them worse but irrelevantly so): it just allows those games to be fixed.

Is anyone volunteering to go change the value of `maxFactoriesPerTerritory` of the Global game (and possibly of all games of that map as well as all games of the Europe 1940 and Pacific 1940 maps) from `2` to `1` after the PR is merged? **I intend to do it for Civil War: it's an unpopular map so not much risk, so we can have at least a real application of this fix.**

---

Please @asvitkine check and confirm everything I said is true. I'm not able actually to read what you are doing in the code.

**Comment by VictoryFirst2** [comment]
@Cernelius Can't add anything to that, you perfectly broke down the situation. It comes down to 1) make sure everyone updates TripleA first 2) then make sure everyone updates the map. The only real problems arrive when 2) happens before 1). Any other combination results in virtually no (additional) problems.

**Comment by VictoryFirst2** [comment]
The fix PR has finally been merged, which means the engine will allow you to place factory_upgrades in Global 1940 even when maxFactoriesPerTerritory is set to 1.

However, to fully fix this issue, the relevant XMLs need to be updated as outlined by @Cernelius above. We probably need to discuss how to best do this, as people definitely need the engine update before they update their map.

cc @panther2

**Comment by Cernelius** [comment]
@VictoryFirst2 Great!

If you can, maybe also updating the title of this issue would be good.

I'm taking a serious look at Civil War, with the intention (hopefully, not promising) to update it about this issue, but I'm also strongly considering fixing a bunch of other reported issues about this game at the same time, as well as making some corrections to the notes.

In case of Civil War, there is little doubt about what needs to be done as the game-maker was graceful enough to document the "hack". From the notes of "Civil War: A House Divided":
>Although upgradable constructions have territory limit per category, such as civilian economies (limit 1) or fieldworks (breastwork, entrenchments, fortifications, limit 3), there is actually an extra slot to allow for upgrading, since the new unit is placed before the old unit is consumed. Please observe rules in the notes and on the unit chart regarding placement limits.

However, I see no hack at all in case of fieldworks: it seems to me that they already work as intended (max 1 per type of fieldwork so up to 3 per territory because there are 3 types in total), so I guess I'm leaving these alone as they are.

**Comment by Cernelius** [comment]
If I update Civil War (or any map I do not own, for example "The Pact of Steel"), who would be able to merge my pull request there? Would @DanVanAtta do it, or can @VictoryFirst2 do it too? I'm asking because I hope I'm not going to do the work to update it just to end up having done it for nothing. Is @RogerCooper able to accept PR on maps? May I know who is?

**Comment by RogerCooper** [comment]
I should be able to accept the PR or upload the corrected XML myself.

**Comment by Cernelius** [comment]
> I should be able to accept the PR or upload the corrected XML myself.

Cool. I'll also ask in here if anyone is open to playtest Civil War after (if) I make the changes to see if there are problems? Unfortunately, I'm not a player of this map. (It's not a big deal, because I believe that almost nobody plays this map, and they can report problems of course.)

I hope to do it Sunday, but I'm not actually promising anything.

**Comment by VictoryFirst2** [comment]
@Cernelius All five people listed here would be able to merge PRs on maps for you:
https://github.com/orgs/triplea-game/teams/map-admin

>Cool. I'll also ask in here if anyone is open to playtest Civil War after (if) I make the changes to see if there are problems? 

What are the exact bugs you would like to fix? If you want, you can open an issue detailing all the bugs that need to be fixed about that map and we could help.

> If you can, maybe also updating the title of this issue would be good.

To what would you like me to update the title to?

**Comment by Cernelius** [comment]
> [@Cernelius](https://github.com/Cernelius) All five people listed here would be able to merge PRs on maps for you: https://github.com/orgs/triplea-game/teams/map-admin
> 
> > Cool. I'll also ask in here if anyone is open to playtest Civil War after (if) I make the changes to see if there are problems?
> 
> What are the exact bugs you would like to fix? If you want, you can open an issue detailing all the bugs that need to be fixed about that map and we could help.

No, I meant that there are other things to fix in the game file and I would do that myself (as I've already done for that game in the past: you can see the changelog). I was just asking if there was anyone volunteering to playtest the map after I fix it (if I do), but I also found at least one user in the lobby that is a veteran of the map.

> > If you can, maybe also updating the title of this issue would be good.
> 
> To what would you like me to update the title to?

I don't have a preference. I was just thinking that the title is not on spot, but change or leave it be as you prefer. (It does not actually matter.)
