### ISSUE TITLE
sub blocked by cruiser

### ISSUE THREAD

**Issue by limo49** [triplea-game/triplea#6114]
Engine Version: 1.9.0.0.13066
Map Name: World War II Global 1940 2nd Edition
Map Version: 4.0

- start a local game and get all human players
- pass all phases/turns until the UK NCM phase
- move the UK cruiser from 91 to 94
- move the UK transport from 109 to 91
- pass all phases/turns until the Italian CM phase
- move the sub from 95 to 94
- try to move the sub from 94 to 92

TripleA says "Not all units have enough movement"

The sub should ignore the UK cruiser in 94 and attack the UK transport in 91.

[test.zip](https://github.com/triplea-game/triplea/files/4403748/test.zip)

**Comment by panther2** [comment]
Addition:
In order to make this move work correctly, you need to perform it as follows:
- select the Italian sub in SZ 95
- press "Ctrl' and left-klick the sub in SZ 94
- proceed the sub to SZ 91

**Comment by limo49** [comment]
Ok it works
Thanks

Maybe it should work even moving one step at a time...

**Comment by panther2** [comment]
> Maybe it should work even moving one step at a time...

Actually it would work that way, but in this special case TripleA for any reason chooses to move through SZ 93 (instead of 94) which is not possible as there is a french destroyer blocking the move.

That's an issue of "strange movement".

**Comment by beelee1** [comment]
@limo49 @panther2 
so all good here ? probably can be closed ?

**Comment by panther2** [comment]
@beelee1 

I think I provided a workaround for situations like this.
In general the reported issue is valid.

**Comment by limo49** [comment]
> So is the wayfinding problematic, too.

Please note that I'm not trying to move the sub directly from 95 to 91 (I see the proposed path blocked by the French destroyer).
I'm moving it one sea zone at time from 95 to 94, then to 92 and finally 91.

**Comment by Cernelius** [comment]
>> Maybe it should work even moving one step at a time...
> 
> Actually it would work that way, but in this special case TripleA for any reason chooses to move through SZ 93 (instead of 94) which is not possible as there is a French destroyer blocking the move.
>
> That's an issue of "strange movement/wayfinding".

@panther2 Did you test the savegame he/she provided? To me it doesn't work one step at a time: the sub is blocked right at the first step (in sea zone 94 sea zone).

**Comment by panther2** [comment]
@Cernelius Yes, that is exactly what I said here: https://github.com/triplea-game/triplea/issues/6114#issuecomment-606099518

It would work correctly if TripleA didn't choose a different path. 

@limo49 Yes, that is why I addressed both issues: (block and wayfinding).

**Comment by Cernelius** [comment]
I guess the block is a problem and smarter wayfinding is a feature request, though one could argue that if you can go directly from A to D through B and C, you should really do so, instead of needlessly splitting the movement into two or three actions (also keeps history cleaner), shouldn't you?

If you are playing on board, an someone moves from A to B, then takes his hand off, then moves the same unit from B to C, then takes his hand off, then moves the same unit from C to D, wouldn't you ask him why the hell didn't he simply move directly from A to D (and just telling the path, if relevant for retreat)?

**Comment by panther2** [comment]
Not going to argue too much abiut bug or feature request, but in the given case, I would consider the path through SZ 93 as being incorrect, while the path through SZ 94 is the only correct one.

**Comment by frigoref** [comment]
@panther2, @beelee1 @limo49, @Cernelius Is this still open? If so, could anyone please provide a new saved game and step-by-step guide to reproduce the issue?

**Comment by limo49** [comment]
I tried again with Engine Version: 2.5.22294
The problem is still present and the steps to reproduce are the same in my first post
Below is a new savegame at the Italian CM, so the remaining steps are:
- move the sub from 95 to 94
- try to move the sub from 94 to 92


[2025-5-23-World-War-II-Global-1940-2nd-Edition.zip](https://github.com/user-attachments/files/20415773/2025-5-23-World-War-II-Global-1940-2nd-Edition.zip)

**Comment by frigoref** [comment]
@limo49 I am not sure what exactly you expect from the engine compared to what you experience and what you reasoning behind this is. Could you please clarify this?
My test result show that currently 
1. You can do the first step, i.e., the move of the Italian sub from SZ 95 to 94, and get this results in a combat move as expected.
2. When trying the second step, i.e., the move of the same Italian sub from SZ 94 to 92, the message panel shows in red "Not all units have enough movement", which I consider also as expected behavior as the British destroyer has scouted the sub and it therefore has to fight, resolved in TripleA by setting the Movement count to 0.

**Comment by limo49** [comment]
@frigoref in SZ 94 there is a cruiser (not a destroyer), so the sub should pass (and attack the transport in 91)

**Comment by limo49** [comment]
I tested it with version **2.7.15032**, and here's what I observed:

* **Scenario 1: Forced Path (CTRL+click)**
    If I select the submarine in **zone 95** and then **CTRL+click** on **zone 94** (to force a specific path), all moves are possible. This behavior is **OK**.

* **Scenario 2: Automatic Pathing with Obstruction**
    If I select the submarine in **zone 95** and move the mouse to **zone 91**, the suggested path crosses **zone 93**. The move is then blocked with the message "Cannot move submarines under destroyers" due to a French destroyer in zone 93. This could be considered **acceptable if the user is aware of the CTRL+click option** for manual pathing. Ideally, the system should **automatically propose a valid path** from all available legal routes, if any exist.

* **Scenario 3: Insufficient Movement Points**
    If I move the submarine from **zone 95** to **zone 94** (which contains a UK cruiser) and then try to move the submarine again from **zone 94**, all subsequent moves are impossible due to the message "Not all units have enough movement."

**Comment by limo49** [comment]
I tried again but the problems are always the same:
- **Scenario 2**: If I click the sub in 95 and move the mouse to 91, the proposed path crosses 93, which is **incorrect**. I can't get what's shown in the screenshot, except by manually forcing the path.
- **Scenario 3**: The sub hasn't started any battle with any destroyer: there's a cruiser, **not a destroyer**, in 94.

Here is a new savegame with 2.7.15032

[2025-6-1-World-War-II-Global-1940-2nd-Edition.zip](https://github.com/user-attachments/files/20540127/2025-6-1-World-War-II-Global-1940-2nd-Edition.zip)

**Comment by frigoref** [comment]
@limo49 You would have to wait for the next pre-release as stated with

> You would need to use a TripleA Version > [2.7.15032](https://github.com/triplea-game/triplea/tree/2.7.15032) or after the date of this comment.

Also, in Scenario 3 it does not matter against which enemy unit the battle was started. There is no automatism to leave the battle and change the original move that lead to the battle. Hence, it works as designed so far. If you think it is valuable to have such an automatism, please raise a separate feature request.

**Comment by limo49** [comment]
The auto path issue has been resolved.
As for the insufficient movement points, I agree that it can stay as it is.
Thanks
