### ISSUE TITLE
Many file problems with latest update

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#7918]
When opening the program I immediately receive the following error:

Unexpected error reading XML file: jar:file:/C:/Users/Roger/triplea/downloadedMaps/crazygs_ww1-master.zip!/crazygs_ww1-master/map/MovementTriggers.xml, ParseError at [row,col]:[1,1] Message: Premature end of file.  javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1] Message: Premature end of file.  If this problem happens frequently and is something you cannot fix, please report it to TripleA 

Also a map I was working on in unzipped form does not appear in the map selection list.

And I mod called WW2v3_Bad-Ass_4_Nation_FFA.zip appears 14 times on the selection list and will not run on any of them.

**Comment by RogerCooper** [comment]
This is with version 22024

**Comment by FrostionAAA** [comment]
At least the problem with unzipped maps not showing has been fixed in #7904 as far as I know Right, @RogerCooper?

**Comment by trevan** [comment]
This is caused by https://github.com/triplea-game/triplea/pull/7617.  @DanVanAtta made a change to read all *.xml files in any directory inside of the zip file instead of just games/map/*.xml.  Your file `MovementTrippers.xml` ends with `.xml` and so it tries to parse it as a game file and fails.  That's where the error messages are coming from.  And I bet you have 14 `xml` files in your zip and the UI is showing one entry for each `xml`.

**Comment by trevan** [comment]
@RogerCooper , I just downloaded the crazygs_ww1-master in the latest pre-release and I didn't see any errors.  I also checked the zip file and I don't see a `MovementTriggers.xml` file.  Are you using a modified map?

Can you retry using the latest prerelease and see if these errors are still happening?  If they are, can you upload the zips (for both maps you mentioned)?

**Comment by DanVanAtta** [comment]
FWIW, this problem will be solved more systematically with the introduction of the `map.yml` file that will explicitly index any XML files that are to be considered game files.
